### PR TITLE
Spec changes

### PR DESCRIPTION
**Pull request by fanchen1988**
@chen-factual 

Before I pushed out all changes on write, could you have a review on the spec changes? I actually changed a lot on spec during I implement the write operations and fetch core. After the spec is confirmed, I'll refactor the rest code and fetch core accordingly and push them.

### CODE REVIEW

**Comment by chen-factual** [comment]
Thanks @fanchen1988, excited to have this!

A few things:
1) Can we make a new doc for `write-options.md`? We have very query specific options like "offset" and "sort" in the current doc.
2) Why do we need all of "insert", "update", and "upsert"? I'm personally happy to just support upsert and make our interface simpler.
3) Instead of having a "RAW_*" set of write operations, can we have a flag for `raw = true` and then go down a different code path?

I'll be online late tonight, I'd like to chat about this before going forward if you're free?

**Comment by fanchen1988** [comment]
1.) I'm not sure about this. `singleRow` seems just for write. But the `primaryField`, for now it's for `upsert`(`INSERT INTO ... ON CONFLICT ()`), and `singleRow`, but I set it as a general name(`primaryField`) in case it can be used as other purposes. Do you think any other query operation needs the `primaryField`?

2.) At first I wanted to make the interface complete(includes all write operations), simple purpose(respectively just for `insert`, `update`, `remove` or `upsert`), fixed structure(`insert` always needs just an insert doc, `update` always needs query and update, `remove` just needs a query), and unified interface(no matter what the backend is). But I found it's really difficult to make the `upsert` unified for Postgres and Mongo, because they're based on totally different actions.
So your proposal is that we just keep `upsert`(except for `remove`)? But how do we do insert and update? By specifying different parameters?(like it's an Insert if there's a `insert` field, and an Update if there's a `update` field?) I'm worried about it'll make the interface confusing because diverse params will make the interface action totally different. If the `upsert` is too complicated, could we just get rid of the `upsert` and keep `insert` and `update`?
Let's talk more about this tomorrow.

3.) We need a flag field to specify which raw action it is, because Mongo db back-end need to know which method it should call. I understand we have too many `TYPES` here, may be we can specify different field to distinguish them? Like `raw-insert`, `raw-update`?

**Comment by fanchen1988** [comment]
Ok @chen-factual , here is the wrap up on FrancaJS discussing today, I may change something a little in details. Let me know if I miss or make something wrong.

0.) Still keep read and write options in the same field, and keep their docs in the same doc(which should be `docs/query-options.md`), but put them into 2 different sections, for read and write option respectively.

1.) We still keep remove as it is:

```
{
  "type": "REMOVE",
  "query": {},
  "options": {}
}
```

and keep update as it is:

```
{
  "type": "UPDATE",
  "query": {},
  "write": {},
  "options": {}
}
```

Note that the update doc will be implicitly added an `$set` operator.
We will integrate upsert function into insert though. When we just need to insert a doc:

```
{
  "type": "INSERT",
  "write": {},
  "options": {}
}
```

The `write` here is just pure key/value pairs. For Mongo it'll be translated to an Insert action, and the `write` is the inserted doc. And for Postgres, it's a pure insert also.
If users want to do an upsert, just add a `upsert` field, as following:

```
{
  "type": "INSERT",
  "write": {},
  "upsert": {},
  "options": {}
}
```

For Postgres, this means an insert query, the key/value pairs in `write` is the inserted doc, and the doc in `upsert` will be translated as a `ON CONFLICT () DO` statement.
For Mongo, this means an update query, the `upsert` is a FrancaJS query which will be translated as the `query` in update, and the `write` would be the `update` doc, with an additional `{"upsert": true}` option.

2.) We remove all `RAW_*` types for raw writes, just assign `RAW` to them, and specify action by suffixing the action name to the `raw` field, example:

```
{
  "type": "RAW",
  "raw-insert": {}
}
```

means a raw insert

3.) We should specify the specific action type to translated query object, this is necessary for Mongo query, because Mongo backend adapter needs to know which db method it should use. Like:

```
{
  "type": "update",
  "query": {},
  "update": {},
  "options": {
    "upsert": true
  }
}
```

**Comment by chen-factual** [comment]
> If users want to do an upsert, just add a upsert field, as following:

What's the difference between the `write` and `upsert` payloads in this case? Can `upsert` just be a boolean flag?

> and specify action by suffixing the action name to the raw field, example:

I think having so many different field names (the "raw-*"s) is a bit heavy handed. We can keep the API more elegant by having a "raw" field for the query itself and a "raw_action" field denoting if we're doing a "read", "upsert", etc.

Btw, for Javascript I think I prefer camelCase or snake_case over lisp-case, because you can do `obj.innerObj` or `obj.inner_obj`, but you have to write `obj['inner-obj']` for lisp-case. Generally speaking though, I prefer lisp-case as I don't have to hit the shift key :)

**Comment by fanchen1988** [comment]
> What's the difference between the write and upsert payloads in this case? Can upsert just be a boolean flag?

When it's `INSERT`, both Mongo and Postgres `write` is a hash of key/value pairs that needs to be inserted. When we want an upsert, Postgres `write` still denotes the insert doc, and `upsert` is the update doc. And for Mongo, the doc of `write` actually becomes the `update` doc, and `upsert` is a query. It's a little difficult to find an appropriate name for both `update`(Postgres) and `query`(Mongo) meaning. Since I chose `upsert` as a doc I just omit the `upsert: true`. Do you have any suggestion on naming the field?

> I think having so many different field names (the "raw-*"s) is a bit heavy handed. We can keep the API more elegant by having a "raw" field for the query itself and a "raw_action" field denoting if we're doing a "read", "upsert", etc.

So this is kind of the same worrying I said yesterday, I'm worried about if it makes a Franca query too complicated? That has more and more field. And I think this is another blowing up with too many TYPES?

**Comment by fanchen1988** [comment]
Oh wait! I just realised a problem @chen-factual ! Theoretically, an INSERT should allow inserting multiple docs, if it becomes an `update` in update action, it will throw error right?

**Comment by fanchen1988** [comment]
@chen-factual how about we make `update` cover the `upsert` case. For mongo, it's easy, user just specify an `upsert: true` in option, then it's done. For Postgres, when users specify the `upsert: true`, Franca will expect an `insert` field(instead of `query`). The only problem is that the Postgres `UPDATE` operation has arbitrary keys(`query` and `update` when update, `insert` and `update` when upsert), but I think this is better than significance changes?(if we make INSERT cover UPSERT, for Mongo, the `write` denotes insert but becomes update in another case)

**Comment by fanchen1988** [comment]
Thought through this more, I take some feasible examples as comparison between `INSERT` and `UPDATE` covers `UPSERT`:

0.) if `INSERT` covers `UPSERT`
  a.) when do Insert operation:

``` json
{
  "mongo": {
    "type": "INSERT",
    "write": [{}, {}]        // Denotes Insert Doc
  },
  "postgres": {
    "type": "INSERT",
    "write": [{}, {}]        // Denotes Insert Doc
  }
}
```

  b.) when do upsert operation:

``` json
{
  "mongo": {
    "type": "INSERT",
    "upsert": true,
    "write": [{}, {}],  // Denotes Update Doc
    "payload": {}  // Denotes Query Doc
  },
  "postgres": {
    "type": "INSERT",
    "upsert": true,
    "write": [{}, {}],  // Still Denotes Insert Doc
    "payload": {}  // Denotes Update Doc
  }
}
```

1.) if `UPDATE` covers `UPSERT`:
  a.) when do update operation:

``` json
{
  "mongo": {
    "type": "UPDATE",
    "base": {},  // Denotes Query Doc
    "write": {}  // Denotes Update Doc
  },
  "postgres": {
    "type": "UPDATE",
    "base": {},  // Denotes Query Doc
    "write": {}  // Denotes Update Doc
  }
}
```

  b.) when do upsert operation:

``` json
{
  "mongo": {
    "type": "UPDATE",
    "upsert": true,
    "base": {},  // Still Denotes Query Doc
    "write": {}  // Still Denotes Update Doc
  },
  "postgres": {
    "type": "UPDATE",
    "upsert": true,
    "base": {},  // Denotes Insert Doc
    "write": {}  // Still Denotes Update Doc
  }
}
```

I think the insert covers upsert approach is more intuitive?

**Comment by fanchen1988** [comment]
Hi @chen-factual , I've changed the spec accordingly, based on what I suggested(`update` covers `upsert` instead of `insert`), and removed all `RAW_***` types, added action_types to denote the write operation type.

Could you help me have a look at it? Thanks!

**Comment by chen-factual** [comment]
@fanchen1988 
Thanks for the clear examples for both postgres and mongo updates; yep the update + upsert looks better. Since `base` refers to query for the update case, can we just call that the query? That would make it more in line with the regular read queries anyway.

**Comment by fanchen1988** [comment]
You are right, it's clearer for update, but what's for the upsert? base?
What I thought is that for one specific type we should try to keep the
schema as stable as possible. Would it be confusing if it's query for
update, and becomes base when we add a `upsert: true`?

**Comment by chen-factual** [comment]
I'm saying we can just keep it as query, just for consistency.

**Comment by fanchen1988** [comment]
I dont know, is it a little strange for Postgres upsert, that we put an
insert doc into `query`?

**Comment by fanchen1988** [comment]
About how to deal with the `upsert`, @chen-factual and I has discussed a lot, here is the wrap up from our Slack discussion:

For `update`, pretty straight forward:

```
{
  "type": "UPDATE",
  "table": "db",
  "query": {
    "type": "AND",
    "queries": [{
      "field": "foo",
      "match": 1
    }, {
      "field": "bar",
      "match": 2
    }]
  },
  "write": {
    "bar": 3,
    "test": 4
  }
}
```

Translation:
Mongo: `db.update({"foo": 1, "bar": 2}, {"$set": {"bar": 3, "test": 4}})`.
Postgres: `UPDATE db SET bar = 3, test = 4 WHERE (foo = 1 AND bar = 2)`.

For Mongo `upsert`:

```
{
  "type": "UPDATE",
  "table": "db",
  "upsert": true,
  "query": {
    "type": "AND",
    "queries": [{
      "field": "foo",
      "match": 1
    }, {
      "field": "bar",
      "match": 2
    }]
  },
  "write": {
    "bar": 3,
    "test": 4
  }
}
```

Translation: `db.update({"foo": 1, "bar": 2}, {"$set": {"bar": 3, "test": 4}}, {"upsert": true})`

As for Postgres `upsert`: We translate it as an `insert into on conflict` statement, but this statement itself could be very complicated so that be far away from our `upsert` semantics. For example: `INSERT INTO table (f1, f2, f3) VALUES (v1, v2, v3) ON CONFLICT (f1) DO UPDATE f1=v4, f3=v5, f4=v6`. This statement actually implies 3 queries:
0.) Query if there are rows match `{f1: v1}`
1.) If no then insert `{f1: v1, f2: v2, f3: v3}`
2.) Otherwise update rows that `{f1: v1}` with `{f1: v4, f3: v5, f4: v6}`

So if users want to do something complicated like above, they should use `RAW` because this kind of semantics are not common among other kinds of dbs(within one query). So for Postgres `upsert`, we should follow 2 constraints:

0.) The `query` could only be i.) a single match query or ii.) an `AND` compound `queries`, each sub query of which is a single match query.
i.e. should not use type/keywords including but not limited to like `RAW`, `OR`, `regex`, `facet`, `range` and so on. In other words, the `query` could be translated to a simple object that only contains keys(fields) and values.
1.) `query`(the translated simple k/v version) and `write`(must be an object of k/v pair) are not allowed having field that are collided in value, like `{"query": {"foo": 1}, "write": {"foo": 2}}` is forbidened, but `{"query": {"foo": 1}, "write": {"foo": 1}}` is ok.

Either constraint is detected, FrancaJS will raise an exception and suggest users to use `RAW`

So a valid FrancaJS Postgres query should look like this:

```
{
  "type": "UPDATE",
  "table": "db",
  "upsert": true,
  "query": {
    "type": "AND",
    "queries": [{
      "field": "foo",
      "match": 1
    }, {
      "field": "bar",
      "match": 2
    }]
  },
  "write": {
    "bar": 2,  // Or this line could be omitted
    "test1": 3,
    "test2": 4
  }
}
```

FrancaJS will merge the `query` and `write` as the insert values, and use the fields of `query` as the conflict target. Here is the translation:
`INSERT INTO db (foo, bar, test1, test2) VALUES (1, 2, 3, 4) ON CONFLICT (foo, bar) DO UPDATE test1 = 3, test2 = 4`.

We believe that even we set this kind of constraint, we still can cover most use cases and make the query performacen optimization and safe(other approaches like CTE or sub query will cause a bad performace or have a certain chance to race condition).

**Comment by fanchen1988** [comment]
@chen-factual let me know thought about the latest spec change, will push the component change once the spec is good to merge.

**Comment by chen-factual** [comment]
Looks good to me, thanks for the hard work @fanchen1988. This was pretty tough to figure out and I think you've led us to a good place on this.

**Pull request merged**
